// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADircDHTQ6HAKubFmZxrYSHVmB4f0Hk7I',
    appId: '1:919983232242:web:9f06a2fbfdfdddf1a96c6b',
    messagingSenderId: '919983232242',
    projectId: 'commissionappareldb',
    authDomain: 'commissionappareldb.firebaseapp.com',
    storageBucket: 'commissionappareldb.firebasestorage.app',
    measurementId: 'G-RPME0ZQL11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyOsX361xbJq0F5kPv1ppowJGlV0HRY0s',
    appId: '1:919983232242:android:24ef007bddad7af7a96c6b',
    messagingSenderId: '919983232242',
    projectId: 'commissionappareldb',
    storageBucket: 'commissionappareldb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrGhBDB550m8V5v5WPbXHP8M8O5GWmuxY',
    appId: '1:919983232242:ios:8e3b0609eea6dbb2a96c6b',
    messagingSenderId: '919983232242',
    projectId: 'commissionappareldb',
    storageBucket: 'commissionappareldb.firebasestorage.app',
    iosBundleId: 'com.example.commissionApparelFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrGhBDB550m8V5v5WPbXHP8M8O5GWmuxY',
    appId: '1:919983232242:ios:8e3b0609eea6dbb2a96c6b',
    messagingSenderId: '919983232242',
    projectId: 'commissionappareldb',
    storageBucket: 'commissionappareldb.firebasestorage.app',
    iosBundleId: 'com.example.commissionApparelFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADircDHTQ6HAKubFmZxrYSHVmB4f0Hk7I',
    appId: '1:919983232242:web:23fd615617f46541a96c6b',
    messagingSenderId: '919983232242',
    projectId: 'commissionappareldb',
    authDomain: 'commissionappareldb.firebaseapp.com',
    storageBucket: 'commissionappareldb.firebasestorage.app',
    measurementId: 'G-WPKP4K00WW',
  );
}
